---
title: "Create Predictions"
output: html_notebook
---

This code creates predictions of death rates in the UK. The code uses the following data and estimates:
* start_value is 463, which is the World Health Organization's figure for 26th March 2020.
* daily_growth_rate = 1.25. This is an estimate, based on the observed growth rates so far. Figures double every 3 or 4 days. 

```{r}
library(stringr)
library(readr)
library(dplyr)
```



```{r}
predictor <- function(start_value, daily_rate, days) {
    predicted_value <- start_value * daily_rate * days}
twenty_seventh_march <- predictor(463, 1.25, 1)
twenty_eighth_march <- predictor(463, 1.25, 2)
twenty_ninth_march <- predictor(463, 1.25, 3)
thirtieth_march <- predictor(463, 1.25, 4)
thirty_first_march <- predictor(463, 1.25, 5)
first_april <- predictor(463, 1.25, 6)
second_april <- predictor(463, 1.25, 7)
third_april <- predictor(463, 1.25, 8)
ninth_april <- predictor(463, 1.25, 14)
str_glue("Predicted deaths on 27th March {twenty_seventh_march}")
str_glue("Predicted deaths on 28th March {twenty_eighth_march}")
str_glue("Predicted deaths on 29th March {twenty_ninth_march}")
str_glue("Predicted deaths on 2nd April {second_april}")
str_glue("Predicted deaths on 9th April {ninth_april}")
```

```{r}
predicted_deaths <- c(twenty_seventh_march, twenty_eighth_march, twenty_ninth_march, thirtieth_march, thirty_first_march, first_april, second_april, third_april)
date <- as.Date(c('2020-03-27', '2020-03-28', '2020-03-29', '2020-03-30', '2020-03-31', '2020-04-01', '2020-04-02', '2020-04-03'))
predictions_table <- data.frame(date, predicted_deaths)
nil_results <- c("NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA")
predictions_table <- predictions_table %>% mutate(actual_deaths=nil_results)
predictions_table
```



```{r}
write.csv(predictions_table, 'predictions.csv')
```


